# Generated by Django 2.1.2 on 2019-06-27 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Household items & Electronics', 'Household items & Electronics'), ('Clothing', 'Clothing'), ('Study notes', 'Study notes'), ('Others', 'Others')], max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link_1', models.URLField(blank=True, default='', max_length=1000)),
                ('image_link_2', models.URLField(blank=True, default='', max_length=1000)),
                ('image_link_3', models.URLField(blank=True, default='', max_length=1000)),
                ('image_link_4', models.URLField(blank=True, default='', max_length=1000)),
                ('title', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('N', 'New'), ('USED', 'Used')], default='Not chosen', max_length=255)),
                ('price_in_SGD', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('description', models.TextField(blank=True, null=True)),
                ('this_product_has_multiple_quantities', models.BooleanField()),
                ('delivery_location', models.CharField(choices=[('ONL', 'ONLINE'), ('PGP', "Prince George Park's Residences/ KEVII Hall"), ('KRMRT', 'Kent Ridge MRT'), ('S', 'Science/ UHall'), ('UHC', 'UHC/ RVRC/ YIH'), ('M', 'Museum/Raffles Hall'), ('U', 'UTown'), ('CLB', 'CLB/Engineering'), ('AS', 'FASS/ Eusoff Hall/ Temasek Hall'), ('COM', 'SoC'), ('BIZ', 'Business School/ Kent Ridge Hall/ Sheares Hall')], default='Not yet chosen', max_length=255)),
                ('extra_information', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
