# Generated by Django 2.1.2 on 2019-06-28 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_link_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_link_4',
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
